server:
  port: 8080

spring:
  profiles:
    active: dev
  datasource:
    username: root
    password: 20177600
    url: jdbc:mysql://47.98.240.31:3307/four_admin_mall?userSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    #   数据源其他配置
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
  main:
    allow-bean-definition-overriding: true

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0
  mapper-locations: classpath:mapper/**/*.xml

jwt:
  tokenHeader: Authorization #JWT存储的请求头
  secret: mall-admin-secret #JWT加解密使用的密钥
  expiration: 604800 #JWT的超期限时间(60*60*24*7)
  tokenHead: 'Bearer ' #JWT负载中拿到开头

#  cache:
#    type: redis
#
#  redis:
#    host: 47.98.240.31
#    port: 6379
#    lettuce:
#      pool:
#        max-active: 8 #连接池最大连接数
#        max-idle: 8 #连接池中的最大空闲链接
#        min-idle: 0 #连接池中的最小空闲链接
#        max-wait: 1000  #连接池最大阻塞等待时间
#      shutdown-timeout: 100 #关闭超时时间
#    password: 2017764300

#  security:
#    loginType: json

secure:
  ignored:
    urls: #安全路径白名单
      - /swagger-ui.html
      - /swagger-resources/**
      - /swagger/**
      - /**/v2/api-docs
      - /**/*.js
      - /**/*.css
      - /**/*.png
      - /**/*.ico
      - /webjars/springfox-swagger-ui/**
      - /actuator/**
      - /druid/**
      - /ums/admin/login
      - /ums/admin/register
      - /ums/admin/info
      - /ums/admin/logout
      - /ums/minio/upload